# Generated by Django 5.0.2 on 2024-04-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('manager', 'Менеджер'), ('admin', 'Адміністратор')], default='user', max_length=20),
        ),
    ]
